### ISSUE TITLE
Folder

### ISSUE THREAD

**Issue by MikeyD-rbg** [Suberbia/UltimateChatRestorer#4]
What if I exported every into a folder DataExport_2024-09-02 with the following folders/files inside?
![Screenshot 2024-09-04 152620](https://github.com/user-attachments/assets/76f49446-c426-40ef-ac2b-76b8a575dab4)

**Comment by MikeyD-rbg** [comment]
PS C:\Users\micha\Downloads\UltimateChatRestorer-main\UltimateChatRestorer-main> python "The Ultimate Chat restorer.py"
Traceback (most recent call last):
  File "C:\Users\micha\Downloads\UltimateChatRestorer-main\UltimateChatRestorer-main\The Ultimate Chat restorer.py", line 47, in <module>
    convert_telegram_to_whatsapp('result.json', '_chat.txt')
  File "C:\Users\micha\Downloads\UltimateChatRestorer-main\UltimateChatRestorer-main\The Ultimate Chat restorer.py", line 5, in convert_telegram_to_whatsapp
    with open(telegram_export_path, 'r', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'result.json'

**Comment by Suberbia** [comment]
It looks like the issue you're facing is because the code is designed to work with .json exports from Telegram, not HTML exports. You can try using my other project called "html_to_txt" available [here](https://github.com/Suberbia/html_to_txt) to convert HTML exports to a format that might work better for your needs.

**Comment by MikeyD-rbg** [comment]
Thanks for the speedy reply, do you think I'll be able to import the whole folder?

**Comment by Suberbia** [comment]
While the script won't import images or media, it will definitely be able to import all the text messages.

**Comment by MikeyD-rbg** [comment]
I edited your other script to iterate through the messages and name the .txts sequentially, I've just got this issue now 
![Screenshot 2024-09-04 170536](https://github.com/user-attachments/assets/4e41925a-2532-4fbd-93d4-d859449a3a72)

**Comment by Suberbia** [comment]
Hi, I'm not quite following the issue you're describing, especially since the error seems unrelated to my code. However, here are some quick instructions to ensure everything is set up correctly:

1. **Install Python**: Make sure Python 3.x is installed on your computer. If not, download it from python.org.
2. **Install BeautifulSoup**: This script uses the BeautifulSoup library for HTML parsing. Install it by running `pip install beautifulsoup4` in your command prompt or terminal.
3. **Run the Script**:
   - Save the script as `transform_html_to_whatsapp.py`.
   - Ensure your chat messages are saved in an HTML file (e.g., `messages.html`).
   - Open Command Prompt or Terminal.
   - Navigate to the directory where the script and HTML file are located using `cd path/to/your/directory`.
   - Run the script with `python transform_html_to_whatsapp.py`.

The script should process the HTML file and create a `_chat.txt` file when it completes.

**Comment by MikeyD-rbg** [comment]
I modified your htmltotxt script to iterate through all the folders and messages, but now I'm getting this issue 
![Screenshot 2024-09-04 172702](https://github.com/user-attachments/assets/d8711ba6-2aec-474a-b68a-65af93e3b73e)

**Comment by MikeyD-rbg** [comment]
Does it accept .jsons or just .txt?

**Comment by MikeyD-rbg** [comment]
Any help to try and import all my .html exported chats would be greatly appreciated 👍

**Comment by Suberbia** [comment]
Your export is in .html format. This code only works for .json exports.
Try this instead:
https://github.com/Suberbia/html_to_txt
